- uses: Platane/snk@v3
  with:
    github_user_name: ${{ github.repository_owner }}
    outputs: |
      dist/github-snake.svg
      dist/github-snake-dark.svg?palette=github-dark
      dist/ocean.gif?color_snake=#d97706&color_dots=#fef3c7,#fde68a,#f59e0b,#d97706,#78350f&color_background=#18181b

